# ============================================================
# email_sender.py — RevenueRadar
# ============================================================
# YEH FILE KYA KARTI HAI:
#   Saari generated reports (PDF + Excel) ko email karta hai.
#   Gmail ka use karta hai — App Password chahiye
#   (normal password nahi chalega).
#
# SETUP (ek baar):
#   1. Gmail → Google Account → Security
#   2. "2-Step Verification" ON karo
#   3. "App passwords" → "Mail" → Generate karo
#   4. Woh 16-character password neeche fill karo
#
# RUN: python 05_reports/email_sender.py
# ============================================================

import smtplib
import os
import sys
from email.mime.multipart import MIMEMultipart
from email.mime.text      import MIMEText
from email.mime.base      import MIMEBase
from email               import encoders
from datetime            import datetime

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from config.config import OUTPUT_DIR

# ── EMAIL CONFIG — YAHAN APNA FILL KARO ─────────────────────
SENDER_EMAIL    = "tumhara@gmail.com"       # ← apna Gmail
SENDER_PASSWORD = "xxxx xxxx xxxx xxxx"     # ← App Password (16 chars)
RECEIVER_EMAILS = [
    "tumhara@gmail.com",                    # ← report kisko chahiye
    # "manager@company.com",               # ← aur log add kar sakte ho
]
# ─────────────────────────────────────────────────────────────

def get_report_files():
    """08_output/ se aaj ki reports find karo."""
    if not os.path.exists(OUTPUT_DIR):
        return []

    today   = datetime.now().strftime("%b%Y")
    reports = []

    for f in os.listdir(OUTPUT_DIR):
        full = os.path.join(OUTPUT_DIR, f)
        if os.path.isfile(full) and (f.endswith(".pdf") or
                                     f.endswith(".xlsx")):
            reports.append(full)

    return reports

def build_email_body():
    """HTML email body banao."""
    date_str = datetime.now().strftime("%d %B %Y")
    return f"""
    <html><body style="font-family: Arial, sans-serif; color: #222;">
      <div style="background:#1A3C6B;padding:20px;border-radius:8px 8px 0 0">
        <h2 style="color:white;margin:0">RevenueRadar — Daily Report</h2>
        <p style="color:#aaa;margin:5px 0 0">{date_str}</p>
      </div>
      <div style="padding:20px;border:1px solid #ddd;border-top:none">
        <p>Hi Team,</p>
        <p>Please find attached today's automated reports from <b>RevenueRadar</b>:</p>
        <ul>
          <li>📊 <b>Impact Report</b> — Revenue trends and business impact</li>
          <li>🔮 <b>Prediction Report</b> — 90-day sales forecast</li>
          <li>🎯 <b>Coach Report</b> — Actionable recommendations</li>
          <li>📋 <b>MIS Report (Excel)</b> — Management summary</li>
        </ul>
        <p style="background:#f5f5f5;padding:12px;border-radius:6px">
          <b>Quick Stats:</b><br>
          Report Date: {date_str}<br>
          Generated by: RevenueRadar Automated Pipeline<br>
          Data Source: SQL Server (RevenueRadarDB)
        </p>
        <p>Reports are auto-generated daily at 9 AM. 
           Reply to this email for any clarifications.</p>
        <hr>
        <p style="color:#888;font-size:12px">
          RevenueRadar — Automated BI System | Confidential
        </p>
      </div>
    </body></html>
    """

def send_reports():
    """Reports email karo."""
    print("📧 Email bhejne ki tayari ho rahi hai...")

    # Check config
    if "tumhara@gmail.com" in SENDER_EMAIL:
        print("⚠️  EMAIL CONFIG UPDATE KARO!")
        print("   email_sender.py kholkar SENDER_EMAIL,")
        print("   SENDER_PASSWORD, aur RECEIVER_EMAILS fill karo.")
        print("\n   (Abhi ke liye email skip kar rahe hain...)")
        return False

    # Reports find karo
    report_files = get_report_files()
    if not report_files:
        print("❌ Koi report nahi mili 08_output/ mein.")
        print("   Pehle reports generate karo.")
        return False

    print(f"  Reports attach honge ({len(report_files)} files):")
    for r in report_files:
        print(f"    - {os.path.basename(r)}")

    try:
        # Email object banao
        msg = MIMEMultipart("alternative")
        msg["From"]    = SENDER_EMAIL
        msg["To"]      = ", ".join(RECEIVER_EMAILS)
        msg["Subject"] = (
            f"RevenueRadar Daily Report — "
            f"{datetime.now().strftime('%d %b %Y')}"
        )

        # HTML body attach karo
        msg.attach(MIMEText(build_email_body(), "html"))

        # Files attach karo
        for filepath in report_files:
            filename = os.path.basename(filepath)
            with open(filepath, "rb") as f:
                part = MIMEBase("application", "octet-stream")
                part.set_payload(f.read())
            encoders.encode_base64(part)
            part.add_header(
                "Content-Disposition",
                f"attachment; filename={filename}"
            )
            msg.attach(part)

        # SMTP se bhejo (Gmail)
        print("\n  SMTP se connect ho raha hai...")
        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as smtp:
            smtp.login(SENDER_EMAIL, SENDER_PASSWORD)
            smtp.sendmail(
                SENDER_EMAIL,
                RECEIVER_EMAILS,
                msg.as_string()
            )

        print(f"✅ Email successfully sent to: {', '.join(RECEIVER_EMAILS)}")
        return True

    except smtplib.SMTPAuthenticationError:
        print("❌ Gmail authentication failed!")
        print("   App Password galat hai ya 2FA on nahi hai.")
        return False
    except Exception as e:
        print(f"❌ Email failed: {e}")
        return False


if __name__ == "__main__":
    print("🚀 RevenueRadar — Email Sender Module")
    print("=" * 55)
    success = send_reports()
    if not success:
        print("\n💡 Email setup ke baad dobara chalao.")
    print("\n➡️  Pipeline complete! Sab reports 08_output/ mein hain.")